name: shop_spy

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^6.0.0

  sqflite: ^0.8.4
  path_provider: ^0.3.0

  barcode_scan: ^0.0.4
  image_picker: ^0.4.1

  fluro: ^1.1.0

  image: ^1.1.31

  http: ^0.11.3+16
  quiver: ^0.29.0+1

flutter:

  uses-material-design: true
